parameters:
- name: Solution
  type: string
  default: 'Entities-Customizations'
  values:
   - Entities-Customizations
   - Plugins-Customization
   - Reports-Customization


trigger: none

jobs:
- ${{ if contains(parameters.Solution, 'Entities-Customizations') }}:
  - job: Entities-Customizations
    steps:
    - script: echo Entities-Customizations

- ${{ if contains(parameters.Solution, 'Plugins-Customization') }}:
  - job: Plugins-Customization
    steps:
    - script: echo Plugins-Customization

- ${{ if contains(parameters.Solution, 'Reports-Customization') }}:
  - job: Reports-Customization
    steps:
    - script: echo Reports-Customization